### ISSUE TITLE
Where can we found the KEY please?

### ISSUE THREAD

**Issue by lakano** [bigbluebutton/screenshare-chrome-extension#1]
Hello!
I can found a public key in the developer dashboard, is it the requested KEY ? If yes, it's a multiline key, so, how to put it correctly in your config field please ?
Regards,

**Comment by antobinary** [comment]
Hey @lakano 
The key is at the end of the link to the extension. For the public extension (whitelisting *.bigbluebutton.org) the link is `https://chrome.google.com/webstore/detail/bigbluebutton-screenshare/akgoaoikmbmhcopjgakkcepdgdgkjfbc` and the key is `akgoaoikmbmhcopjgakkcepdgdgkjfbc`

If you are forking this repository and publishing your own extension so you can whitelist your own domains (see https://github.com/bigbluebutton/screenshare-chrome-extension) your link and key would be different but the same pattern is true: `https://chrome.google.com/webstore/detail/NAME_OF_YOUR_EXTENSION/KEY_OF_YOUR_EXTENSION`

Best regards,
Anton
